"""`ph.llm` — the provider-neutral vocabulary, the stream assembler, the seam."""

from __future__ import annotations

from .adapter import AdapterHandle, LlmAdapter, LlmError, LlmRuntime, ResolvedModel
from .assembler import BlockAssembler
from .types import (
    AttachmentRef,
    BlockEnd,
    BlockStart,
    ContentBlock,
    ContextForm,
    Finish,
    FinishReason,
    GenerateOptions,
    LlmCallConfig,
    LlmCallConfigAdapterDefaults,
    LlmFailure,
    MediaBlock,
    Message,
    MessageSource,
    ModelSource,
    PluginSource,
    ReasoningBlock,
    ReasoningDelta,
    StreamChunk,
    TextBlock,
    TextDelta,
    TokenUsage,
    ToolCallBlock,
    ToolCallDelta,
    ToolResultBlock,
    ToolSchema,
    ToolSource,
    UsageChunk,
    UserSource,
    attachment_of,
    chunk_from_wire,
    content_from_wire,
    create_assistant_message,
    create_message,
    create_tool_result_message,
    create_user_message,
    is_token_delta,
    new_message_id,
)

__all__ = [
    "AdapterHandle",
    "AttachmentRef",
    "BlockAssembler",
    "BlockEnd",
    "BlockStart",
    "ContentBlock",
    "ContextForm",
    "Finish",
    "FinishReason",
    "GenerateOptions",
    "LlmAdapter",
    "LlmCallConfig",
    "LlmCallConfigAdapterDefaults",
    "LlmError",
    "LlmFailure",
    "LlmRuntime",
    "MediaBlock",
    "Message",
    "MessageSource",
    "ModelSource",
    "PluginSource",
    "ReasoningBlock",
    "ReasoningDelta",
    "ResolvedModel",
    "StreamChunk",
    "TextBlock",
    "TextDelta",
    "TokenUsage",
    "ToolCallBlock",
    "ToolCallDelta",
    "ToolResultBlock",
    "ToolSchema",
    "ToolSource",
    "UsageChunk",
    "UserSource",
    "attachment_of",
    "chunk_from_wire",
    "content_from_wire",
    "create_assistant_message",
    "create_message",
    "create_tool_result_message",
    "create_user_message",
    "is_token_delta",
    "new_message_id",
]
