"""`ph.session` — the append-only log, the surface, and the derived history."""

from __future__ import annotations

from .derive import derive_event_message, derive_transcript
from .events import (
    SESSION_FORMAT_VERSION,
    SURFACE_EVENT_TYPES,
    BatchRef,
    SessionEvent,
    SurfaceIntent,
    SurfaceOp,
    SurfaceReplace,
    is_surface_eligible_type,
    now_ms,
)
from .folds import SessionFoldCache, SessionLog
from .intents import (
    Barrier,
    IntentError,
    IntentKind,
    IntentOrphan,
    IntentRecord,
    OpenIntent,
    Unsettled,
    declare_intent,
    declared_intents,
    extend_index,
    fold_intents,
    is_declared,
    key_of,
    open_intents,
    settled_record,
)
from .journal import Claim, IntentJournal, IntentNotDurable, IntentScope, Prior, intents_of
from .json import InvalidJsonValueError, freeze_json_value
from .known_event_types import (
    IGNORABLE_SESSION_EVENT_TYPES,
    KNOWN_SESSION_EVENT_TYPES,
    LogTypeDeclaration,
    LogTypeError,
    UnknownEventTypeError,
    declare_log_type,
)
from .request_header import (
    EpochHeader,
    RequestContext,
    canonical_header,
    fold_latest,
    fold_request_context,
    fold_request_header,
    header_equals,
)
from .session import (
    Session,
    SessionBatch,
    SessionHeader,
    SessionKind,
    SessionObserver,
    cwd_tag,
    family_for,
)
from .store import (
    SessionForkError,
    SessionStore,
    fork_boundaries,
    is_fork_boundary,
    new_session_id,
    open_turn_at,
    session_written,
    valid_session_id,
)
from .surface import (
    SurfaceError,
    SurfaceFoldReplacement,
    SurfaceFoldResult,
    SurfaceManager,
    fold_surface,
    is_append_surface_event,
    is_in_place_rewrite,
    is_replacement_surface_event,
    is_surface_event,
)

__all__ = [
    "IGNORABLE_SESSION_EVENT_TYPES",
    "KNOWN_SESSION_EVENT_TYPES",
    "SESSION_FORMAT_VERSION",
    "SURFACE_EVENT_TYPES",
    "Barrier",
    "BatchRef",
    "Claim",
    "EpochHeader",
    "IntentError",
    "IntentJournal",
    "IntentKind",
    "IntentNotDurable",
    "IntentOrphan",
    "IntentRecord",
    "IntentScope",
    "InvalidJsonValueError",
    "LogTypeDeclaration",
    "LogTypeError",
    "OpenIntent",
    "Prior",
    "RequestContext",
    "Session",
    "SessionBatch",
    "SessionEvent",
    "SessionFoldCache",
    "SessionForkError",
    "SessionHeader",
    "SessionKind",
    "SessionLog",
    "SessionObserver",
    "SessionStore",
    "SurfaceError",
    "SurfaceFoldReplacement",
    "SurfaceFoldResult",
    "SurfaceIntent",
    "SurfaceManager",
    "SurfaceOp",
    "SurfaceReplace",
    "UnknownEventTypeError",
    "Unsettled",
    "canonical_header",
    "cwd_tag",
    "declare_intent",
    "declare_log_type",
    "declared_intents",
    "derive_event_message",
    "derive_transcript",
    "extend_index",
    "family_for",
    "fold_intents",
    "fold_latest",
    "fold_request_context",
    "fold_request_header",
    "fold_surface",
    "fork_boundaries",
    "freeze_json_value",
    "header_equals",
    "intents_of",
    "is_append_surface_event",
    "is_declared",
    "is_fork_boundary",
    "is_in_place_rewrite",
    "is_replacement_surface_event",
    "is_surface_eligible_type",
    "is_surface_event",
    "key_of",
    "new_session_id",
    "now_ms",
    "open_intents",
    "open_turn_at",
    "session_written",
    "settled_record",
    "valid_session_id",
]
