"""`ph.session` — the append-only log, the surface, and the derived history.

**ph-core's intent kinds are declared by importing this package** (T4): `kinds` is
imported below, statically, so no process can hold a session log without the kinds
repair must settle in it. See `ph.session.kinds` for why they live in a leaf.
"""

from __future__ import annotations

from . import kinds as kinds
from .balance import balanced_cuts, cuts_of, cuts_over, open_call_delta, safe_cutoff
from .derive import derive_event_message, derive_transcript, settle_of
from .events import (
    SESSION_FORMAT_VERSION,
    SURFACE_EVENT_TYPES,
    BatchRef,
    SessionEvent,
    SurfaceIntent,
    SurfaceOp,
    SurfaceReplace,
    is_surface_eligible_type,
    now_ms,
)
from .folds import SessionFoldCache, SessionLog
from .intents import (
    UNSETTLED,
    Barrier,
    IntentError,
    IntentKind,
    IntentOrphan,
    IntentRecord,
    OpenIntent,
    Outcome,
    SettledBy,
    Unsettled,
    abandoned,
    declare_intent,
    declared_intents,
    extend_index,
    fold_intents,
    key_of,
    open_intents,
    outcome_of,
    unsettled,
    unsettled_why,
)
from .journal import Claim, IntentJournal, IntentNotDurable, Prior, intents_of
from .json import InvalidJsonValueError, freeze_json_value
from .known_event_types import (
    AUDIT_ONLY_SESSION_EVENT_TYPES,
    IGNORABLE_SESSION_EVENT_TYPES,
    KNOWN_SESSION_EVENT_TYPES,
    LogTypeDeclaration,
    LogTypeError,
    UnknownEventTypeError,
    declare_log_type,
    is_audit_only,
    known_log_types,
)
from .request_header import (
    EpochHeader,
    RequestContext,
    canonical_header,
    fold_latest,
    fold_request_context,
    fold_request_header,
    header_equals,
)
from .revise import editable_message, origin_of, originals, rewrite, substitute
from .session import (
    Session,
    SessionBatch,
    SessionHeader,
    SessionKind,
    SessionObserver,
    cwd_tag,
    family_for,
)
from .store import (
    SessionForkError,
    SessionStore,
    child_session_id,
    fork_boundaries,
    is_child_id,
    is_fork_boundary,
    new_session_id,
    open_turn_at,
    session_written,
    valid_session_id,
)
from .surface import (
    SurfaceError,
    SurfaceFoldReplacement,
    SurfaceFoldResult,
    SurfaceManager,
    fold_surface,
    is_append_surface_event,
    is_in_place_rewrite,
    is_replacement_surface_event,
    is_stand_in,
    is_surface_event,
    shadowed_by,
)

__all__ = [
    "AUDIT_ONLY_SESSION_EVENT_TYPES",
    "IGNORABLE_SESSION_EVENT_TYPES",
    "KNOWN_SESSION_EVENT_TYPES",
    "SESSION_FORMAT_VERSION",
    "SURFACE_EVENT_TYPES",
    "UNSETTLED",
    "Barrier",
    "BatchRef",
    "Claim",
    "EpochHeader",
    "IntentError",
    "IntentJournal",
    "IntentKind",
    "IntentNotDurable",
    "IntentOrphan",
    "IntentRecord",
    "InvalidJsonValueError",
    "LogTypeDeclaration",
    "LogTypeError",
    "OpenIntent",
    "Outcome",
    "Prior",
    "RequestContext",
    "Session",
    "SessionBatch",
    "SessionEvent",
    "SessionFoldCache",
    "SessionForkError",
    "SessionHeader",
    "SessionKind",
    "SessionLog",
    "SessionObserver",
    "SessionStore",
    "SettledBy",
    "SurfaceError",
    "SurfaceFoldReplacement",
    "SurfaceFoldResult",
    "SurfaceIntent",
    "SurfaceManager",
    "SurfaceOp",
    "SurfaceReplace",
    "UnknownEventTypeError",
    "Unsettled",
    "abandoned",
    "balanced_cuts",
    "canonical_header",
    "child_session_id",
    "cuts_of",
    "cuts_over",
    "cwd_tag",
    "declare_intent",
    "declare_log_type",
    "declared_intents",
    "derive_event_message",
    "derive_transcript",
    "editable_message",
    "extend_index",
    "family_for",
    "fold_intents",
    "fold_latest",
    "fold_request_context",
    "fold_request_header",
    "fold_surface",
    "fork_boundaries",
    "freeze_json_value",
    "header_equals",
    "intents_of",
    "is_append_surface_event",
    "is_audit_only",
    "is_child_id",
    "is_fork_boundary",
    "is_in_place_rewrite",
    "is_replacement_surface_event",
    "is_stand_in",
    "is_surface_eligible_type",
    "is_surface_event",
    "key_of",
    "kinds",
    "known_log_types",
    "new_session_id",
    "now_ms",
    "open_call_delta",
    "open_intents",
    "open_turn_at",
    "origin_of",
    "originals",
    "outcome_of",
    "rewrite",
    "safe_cutoff",
    "session_written",
    "settle_of",
    "shadowed_by",
    "substitute",
    "unsettled",
    "unsettled_why",
    "valid_session_id",
]
