"""`ph.tools` — the registry, the pipeline, and the batch scheduler."""

from __future__ import annotations

from .batch import BatchOutcome, execute_tool_calls, parse_arguments
from .definition import (
    Accept,
    Allow,
    Ask,
    Block,
    Deny,
    ExecutionMode,
    FailureKind,
    PostToolDecision,
    PreToolDecision,
    Respond,
    ToolDefinition,
    ToolExecution,
    ToolExecutionInput,
    ToolExecutionResult,
    ToolFailure,
    ToolModel,
    ToolOutput,
    ToolResult,
    ToolRunContext,
    aborted_result,
    define_tool,
    denied_result,
    error_result,
    text_content,
)
from .errors import (
    TOOL_ABORTED,
    TOOL_ABORTED_BEFORE_DISPATCH,
    TOOL_DENIED,
    HarnessError,
    ToolNotFoundError,
    ToolOutputError,
)
from .json_schema import schema_of, unsupported_keywords, validate_json_schema_value
from .presentation import CardKind, ToolCallView, ToolResultView, simple_views
from .registry import RUN_CODE, PreparedCall, ToolGuard, ToolRestriction, ToolRuntime

__all__ = [
    "RUN_CODE",
    "TOOL_ABORTED",
    "TOOL_ABORTED_BEFORE_DISPATCH",
    "TOOL_DENIED",
    "Accept",
    "Allow",
    "Ask",
    "BatchOutcome",
    "Block",
    "CardKind",
    "Deny",
    "ExecutionMode",
    "FailureKind",
    "HarnessError",
    "PostToolDecision",
    "PreToolDecision",
    "PreparedCall",
    "Respond",
    "ToolCallView",
    "ToolDefinition",
    "ToolExecution",
    "ToolExecutionInput",
    "ToolExecutionResult",
    "ToolFailure",
    "ToolGuard",
    "ToolModel",
    "ToolNotFoundError",
    "ToolOutput",
    "ToolOutputError",
    "ToolRestriction",
    "ToolResult",
    "ToolResultView",
    "ToolRunContext",
    "ToolRuntime",
    "aborted_result",
    "define_tool",
    "denied_result",
    "error_result",
    "execute_tool_calls",
    "parse_arguments",
    "schema_of",
    "simple_views",
    "text_content",
    "unsupported_keywords",
    "validate_json_schema_value",
]
